server:
  port: 9004
spring:
  thymeleaf:
    cache: false
  application:
    name: UserWeb004
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka,http://localhost:10087/eureka
logging:
  level:
    com:
      offcn: debug
#开启feign的熔断功能
feign:
  hystrix:
    enabled: true
#设置熔断超时时间
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000